markdown: rdiscount
permalink: /:title/
url: http://hustcat.github.io
name: YYå“¥
author: hustcat
qq: 395070574
email: hustcat@gmail.com
duoshuo: hustcat
beian: 
cnzz: 
weibo: 
github: hustcat
pygments: true
safe: true
paginate: 20
about: "Hustcat"
